Fix missing argument in idaapi.add_menu_item
The missing argument causes keypatch loading to fail in the following condition:
1- start IDA and load any binary, keypatch starts fine
2- close the binary and open a new one. keypatch fails with:
Failed while executing plugin_t.init():
Traceback (most recent call last):
  File "<IDA>/plugins/keypatch.py", line 1169, in init
    idaapi.add_menu_item("Edit/Patch program/", "Keypatch:: Patcher     (Ctrl+Alt+K)", 0, self.patcher, None)
  File "<IDA>/python/ida_kernwin.py", line 332, in add_menu_item
    return _ida_kernwin.add_menu_item(*args)
TypeError: add_menu_item expected 6 arguments, got 5

This affects at least 6.9 and 6.95.